bf16: true
cutoff_len: 1024
dataset: honeypot_logs
dataset_dir: data
do_train: true
finetuning_type: lora
flash_attn: fa2
gradient_accumulation_steps: 8
learning_rate: 5.0e-05
logging_steps: 1
lora_alpha: 16
lora_dropout: 0
lora_rank: 8
lora_target: qkv_proj
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
model_name_or_path: microsoft/Phi-3-mini-4k-instruct
num_train_epochs: 2.0
optim: adamw_torch
output_dir: saves/Custom/lora/honeypot_phi3
packing: false
per_device_train_batch_size: 16
quantization_bit: 8
report_to: none
save_steps: 100
stage: sft
template: phi
warmup_steps: 0
