bf16: true
cutoff_len: 2048
dataset: honeypot_logs
dataset_dir: data
do_train: true
finetuning_type: lora
flash_attn: fa2
gradient_accumulation_steps: 8
learning_rate: 1.0e-04
logging_steps: 1
lora_alpha: 16
lora_dropout: 0
lora_rank: 8
lora_target: q_proj,v_proj
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
model_name_or_path: NousResearch/Meta-Llama-3-8B-Instruct
num_train_epochs: 3.0
optim: adamw_torch
output_dir: saves/Custom/lora/honeypot_llama3_v3
packing: false
per_device_train_batch_size: 8
quantization_bit: 8
report_to: none
save_steps: 100
stage: sft
template: llama3
warmup_steps: 0
